# Generated by Django 3.2.3 on 2021-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('month_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthdetails',
            name='monthname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
